### PR TITLE
dhcpv6: Fix OPTION_STATUS_CODE parsing

### PR DESCRIPTION
**Pull request by cathay4t**
With current code, all DHCPv6 options after `OPTION_STATUS_CODE` will
got parse error as the decoder of `OPTION_STATUS_CODE` read one extra
bytes which ruin all follow up options.

The status message length of DHCPv6 option `OPTION_STATUS_CODE` should
be the total length minus 2.

The RFC 8414 section 21.13. Status Code Option:

    option-len           2 + length of status-message field.

And the status message `MUST NOT be null-terminated`.

Unit test case included using data captured by wireshark(with DHCP
options sorted).

### CODE REVIEW

**Comment by cathay4t** [comment]
I have tested this patch using below capture data from wireshark of real DHCPv6 flow:


```rust
use dhcproto::Decodable;
use dhcproto::Decoder;

fn main() {
    let raw: Vec<u8> = vec![
        0x02, 0xcb, 0x77, 0x9d, 0x00, 0x01, 0x00, 0x06, 0x1e, 0xed, 0xad, 0xd5,
        0xb5, 0x10, 0x00, 0x02, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x01, 0x2c, 0xa9,
        0x3f, 0x79, 0x16, 0x42, 0xe2, 0x17, 0x84, 0x1a, 0x00, 0x03, 0x00, 0x28,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x00, 0x00, 0x00, 0x69,
        0x00, 0x05, 0x00, 0x18, 0x20, 0x01, 0x0d, 0xb8, 0x00, 0x0a, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x84, 0x00, 0x00, 0x00, 0x78,
        0x00, 0x00, 0x00, 0x78, 0x00, 0x0d, 0x00, 0x09, 0x00, 0x00, 0x73, 0x75,
        0x63, 0x63, 0x65, 0x73, 0x73, 0x00, 0x07, 0x00, 0x01, 0x00, 0x00, 0x17,
        0x00, 0x10, 0x20, 0x01, 0x0d, 0xb8, 0x00, 0x0a, 0x00, 0x00, 0x14, 0x42,
        0xe2, 0xff, 0xfe, 0x17, 0x84, 0x1a,
    ];
    let msg = dhcproto::v6::Message::decode(&mut Decoder::new(&raw)).unwrap();
    for opt in msg.opts().iter() {
        println!("HAHA {:?}", opt);
    }
}

```

**Comment by cathay4t** [comment]
Let me put above code into unit test.

**Comment by cathay4t** [comment]
If possible, please tag new release after this patch. Considering we have `OptionCode::NtpServers` breaking the API, `0.10.0` is expected.

**Comment by leshow** [comment]
Thank you for reporting this and fixing the issue, i'll push a new release out shortly.

**Comment by leshow** [comment]
@cathay4t Ah, I didn't realize a name change had been included in the 0.10.0 release. That is an annoying breaking change to include, apologies. 

In future releases, optioncode names will not change.

**Comment by cathay4t** [comment]
@leshow Thanks for the release! It all works well now.

**Pull request merged**
